use_frameworks!

platform :ios, '10.0'

target 'MFBulletView_Example' do
  pod 'MFBulletView', :path => '../'

  target 'MFBulletView_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
